spring:
  application:
    name: springApp
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/TimeTrackerDb}
    username: ${USER_DB:postgres}
    password: ${PASSWORD_DB:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080